"""initial

Revision ID: 41059b1140e6
Revises: 
Create Date: 2025-11-05 15:15:00.650807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41059b1140e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(50), server_default='active', nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('api_url', sa.String(length=1024), nullable=False),
    sa.Column('clone_url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=255), server_default='main', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('auto_sync', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_polling', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_webhooks', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sync_interval', sa.Integer(), server_default='3000', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('retry_delay', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('last_sync_status', sa.String(50), server_default='pending', nullable=False),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_commit_hash', sa.String(length=128), nullable=True),
    sa.Column('last_commit_message', sa.Text(), nullable=True),
    sa.Column('last_commit_author', sa.String(length=255), nullable=True),
    sa.Column('last_commit_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_sync_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_commits_synced', sa.Integer(), server_default='0', nullable=False),
    sa.Column('meta', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_provider'), 'repositories', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_provider'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
